<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.14">
  <POU Name="MAIN" Id="{e6fa2b58-86f6-4521-8196-c6010dfb509b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_VLS_MOTION(); // So, run the program associated with coupler
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="15" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>